spring:
  datasource:
    url: jdbc:h2:mem:promotions;DB_CLOSE_ON_EXIT=FALSE
    username:
    password:
    driverClassName: org.h2.Driver
    validation-query: SELECT 1 FROM INFORMATION_SCHEMA.SYSTEM_USERS
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show_sql: true

swagger.enabled: true
